### ISSUE TITLE
Update existing entries instead of inserting them as new

### ISSUE THREAD

**Issue by arndt-s** [washeuteessen/washeuteessen-management-api#1]

**Comment by lena-kuhn** [comment]
Haben aus dem insert Befehl ein update gemacht, also der Crawler schreibt jetzt schonmal nichts doppelt in die MongoDB.

**Comment by arndt-s** [comment]
ich überprüfe ob es zur URL schon was gibt, wenn ja wird es aktualisiert, wenn nein angelegt.
